<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXHyijij\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXHyijij/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXHyijij.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXHyijij\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXHyijij\App_KernelDevDebugContainer([
    'container.build_hash' => 'XHyijij',
    'container.build_id' => 'b103127d',
    'container.build_time' => 1615446476,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXHyijij');
